import { scrapeTrends } from '@/lib/apify'
import { generateWeeklyPlan, generatePlanFromPrompt, generatePlanFromImage } from '@/lib/gemini'
import { supabaseAdmin, logSystem } from '@/lib/supabase'
import { getConfig } from '@/lib/config'
import { sendNotification } from '@/lib/telegram'
import { WeeklyPlanJSON } from '@/types'

export type ScoutMethod = 'apify' | 'brainstorm' | 'image'
export interface ScoutPayload {
    persona?: string
    prompt?: string
    imageBase64?: string
    mimeType?: string
}

/** Extracts a clip text from either old string format or new {clip_1, clip_2, clip_3} object format */
function extractClip(slot: any, clipKey: 'clip_1' | 'clip_2' | 'clip_3'): string {
    if (!slot) return ''
    if (typeof slot === 'string') return slot
    if (typeof slot === 'object') return slot[clipKey] || ''
    return ''
}

/**
 * Main Job: The Strategic Scout
 * Runs weekly to plan content based on current trends or AI brainstorm
 */
export async function runWeeklyPlanner(method: ScoutMethod = 'apify', payload: ScoutPayload) {
    const PHASE = `Phase1: Scout (${method})`

    try {
        await logSystem('INFO', PHASE, 'Starting Weekly Planning Job...')
        await sendNotification(`🚀 <b>Nong Kung Agency:</b> Starting Phase 1 (${method})...`)

        let plan: WeeklyPlanJSON
        let rawTrends: any = { method }
        const targetPersona = payload.persona || 'Momo' // Default to Momo safely
        const globalBatchSize = parseInt(await getConfig('PRODUCTION_BATCH_SIZE') || '4')

        if (method === 'apify') {
            rawTrends = await scrapeTrends()
            await logSystem('INFO', PHASE, `Trends scraped successfully for ${targetPersona}`, { hashtags: rawTrends.instagram_hashtags })
            plan = await generateWeeklyPlan(rawTrends, targetPersona, globalBatchSize)
        } else if (method === 'brainstorm' && payload.prompt) {
            rawTrends.details = `Prompt: ${payload.prompt}`
            await logSystem('INFO', PHASE, `Brainstorming with prompt for ${targetPersona}: ${payload.prompt}`)
            plan = await generatePlanFromPrompt(payload.prompt, targetPersona, globalBatchSize)
        } else if (method === 'image' && payload.imageBase64) {
            rawTrends.details = `Reference Image. Instructions: ${payload.prompt || 'None'}`
            await logSystem('INFO', PHASE, `Analyzing reference image for ${targetPersona}...`)
            plan = await generatePlanFromImage(payload.imageBase64, payload.mimeType || 'image/jpeg', payload.prompt, targetPersona, globalBatchSize)
        } else {
            throw new Error('Invalid method or missing requirements in payload')
        }

        await logSystem('INFO', PHASE, 'Content plan generated by Gemini', { items: plan.contents.length })


        // 3. Save to Supabase (Transactional-like approach)

        // a. Insert Weekly Plan
        const { data: weeklyPlan, error: planError } = await supabaseAdmin
            .from('weekly_plans')
            .insert({
                week_start_date: plan.week_start,
                week_end_date: plan.week_end,
                campaign_theme: plan.campaign_theme,
                raw_trends: rawTrends,
                plan_json: plan
            })
            .select()
            .single()

        if (planError) throw planError

        const globalWidth = parseInt(await getConfig('PRODUCTION_WIDTH') || '896')
        const globalHeight = parseInt(await getConfig('PRODUCTION_HEIGHT') || '1152')

        // b. Insert 21 Content Items
        const contentItems = plan.contents.map((item, idx) => {
            // Auto calculate schedule: 3 posts/day at 09:00, 13:00, 19:00 over 7 days
            const dayOffset = Math.floor((item.sequence - 1) / 3)
            const postOfDay = (item.sequence - 1) % 3

            // Assume week_start is the base
            const baseDate = new Date(plan.week_start + 'T00:00:00')
            baseDate.setDate(baseDate.getDate() + dayOffset)

            if (postOfDay === 0) baseDate.setHours(9, 0, 0)
            else if (postOfDay === 1) baseDate.setHours(13, 0, 0)
            else baseDate.setHours(19, 0, 0)

            return {
                weekly_plan_id: weeklyPlan.id,
                sequence_number: item.sequence || idx + 1,
                content_type: item.content_type || 'Post',
                persona: item.persona || targetPersona,
                storyline: item.storyline || plan.campaign_theme || 'General',
                topic: item.topic || 'Untitled Topic',
                theme: item.theme || plan.campaign_theme || 'Default Theme',
                sfw_prompt: item.sfw_prompt || '',
                prompt_structure: {
                    mood_and_tone: item.prompt_structure?.mood_and_tone || '',
                    vibe: item.prompt_structure?.vibe || '',
                    lighting: item.prompt_structure?.lighting || '',
                    outfit: item.prompt_structure?.outfit || '',
                    camera_settings: padArray(item.prompt_structure?.camera_settings, globalBatchSize),
                    poses: padArray(item.prompt_structure?.poses, globalBatchSize),
                    nsfw_prompts: padArray(item.prompt_structure?.nsfw_prompts, globalBatchSize),
                    vdo_prompts: padArray((item.prompt_structure as any)?.vdo_prompts, globalBatchSize, { clip_1: '', clip_2: '', clip_3: '' }),
                    vdo_prompts_nsfw: padArray((item.prompt_structure as any)?.vdo_prompts_nsfw, globalBatchSize, { clip_1: '', clip_2: '', clip_3: '' })
                },
                nsfw_option: !!item.nsfw_option,
                gen_sfw: true,
                gen_nsfw: false,
                post_to_ig: true,
                post_to_x: false,
                post_to_fanvue: false,
                caption_draft: item.caption_draft || '',
                scheduled_at: baseDate.toISOString(),
                batch_size: globalBatchSize,
                image_width: globalWidth,
                image_height: globalHeight,
                status: 'Draft',
                image_prompts: item.prompt_structure || {},
                // Handle new clip_1/2/3 object format — extract first clip as the base summary vdo_prompt
                vdo_prompt: extractClip(item.prompt_structure?.vdo_prompts?.[0], 'clip_1') || '',
                vdo_prompt_nsfw: extractClip(item.prompt_structure?.vdo_prompts_nsfw?.[0], 'clip_1') || ''
            }
        })

        const { error: itemsError } = await supabaseAdmin
            .from('content_items')
            .insert(contentItems)

        if (itemsError) throw itemsError

        await logSystem('SUCCESS', PHASE, `Weekly plan created successfully. ID: ${weeklyPlan.id}`)
        await sendNotification(`✅ <b>Phase 1 Complete:</b> Generated 21 content ideas for the week of ${plan.week_start}. Status: <b>Draft</b>`)

        return { success: true, planId: weeklyPlan.id }
    } catch (error: any) {
        await logSystem('ERROR', PHASE, 'Current job failed', { error: error.message })
        await sendNotification(`❌ <b>Phase 1 Error:</b> ${error.message}`)
        return { success: false, error: error.message }
    }
}

function padArray(arr: any[] | undefined, length: number, defaultValue: any = '') {
    const newArr = [...(arr || [])]
    while (newArr.length < length) newArr.push(defaultValue)
    return newArr.slice(0, length)
}
