import { scrapeTrends } from '@/lib/apify'
import { generateWeeklyPlan, generatePlanFromPrompt, generatePlanFromImage } from '@/lib/gemini'
import { supabaseAdmin, logSystem } from '@/lib/supabase'
import { sendNotification } from '@/lib/telegram'
import { WeeklyPlanJSON } from '@/types'

export type ScoutMethod = 'apify' | 'brainstorm' | 'image'
export interface ScoutPayload {
    persona?: string
    prompt?: string
    imageBase64?: string
    mimeType?: string
}

/**
 * Main Job: The Strategic Scout
 * Runs weekly to plan content based on current trends or AI brainstorm
 */
export async function runWeeklyPlanner(method: ScoutMethod = 'apify', payload: ScoutPayload) {
    const PHASE = `Phase1: Scout (${method})`

    try {
        await logSystem('INFO', PHASE, 'Starting Weekly Planning Job...')
        await sendNotification(`🚀 <b>Nong Kung Agency:</b> Starting Phase 1 (${method})...`)

        let plan: WeeklyPlanJSON
        let rawTrends: any = { method }
        const targetPersona = payload.persona || 'Momo' // Default to Momo safely

        if (method === 'apify') {
            rawTrends = await scrapeTrends()
            await logSystem('INFO', PHASE, `Trends scraped successfully for ${targetPersona}`, { hashtags: rawTrends.instagram_hashtags })
            plan = await generateWeeklyPlan(rawTrends, targetPersona)
        } else if (method === 'brainstorm' && payload.prompt) {
            rawTrends.details = `Prompt: ${payload.prompt}`
            await logSystem('INFO', PHASE, `Brainstorming with prompt for ${targetPersona}: ${payload.prompt}`)
            plan = await generatePlanFromPrompt(payload.prompt, targetPersona)
        } else if (method === 'image' && payload.imageBase64) {
            rawTrends.details = `Reference Image. Instructions: ${payload.prompt || 'None'}`
            await logSystem('INFO', PHASE, `Analyzing reference image for ${targetPersona}...`)
            plan = await generatePlanFromImage(payload.imageBase64, payload.mimeType || 'image/jpeg', payload.prompt, targetPersona)
        } else {
            throw new Error('Invalid method or missing requirements in payload')
        }

        await logSystem('INFO', PHASE, 'Content plan generated by Gemini', { items: plan.contents.length })


        // 3. Save to Supabase (Transactional-like approach)

        // a. Insert Weekly Plan
        const { data: weeklyPlan, error: planError } = await supabaseAdmin
            .from('weekly_plans')
            .insert({
                week_start_date: plan.week_start,
                week_end_date: plan.week_end,
                raw_trends: rawTrends,
                plan_json: plan
            })
            .select()
            .single()

        if (planError) throw planError

        // b. Insert 21 Content Items
        const contentItems = plan.contents.map((item) => {
            // Auto calculate schedule: 3 posts/day at 09:00, 13:00, 19:00 over 7 days
            const dayOffset = Math.floor((item.sequence - 1) / 3)
            const postOfDay = (item.sequence - 1) % 3

            // Assume week_start is the base
            const baseDate = new Date(plan.week_start + 'T00:00:00')
            baseDate.setDate(baseDate.getDate() + dayOffset)

            if (postOfDay === 0) baseDate.setHours(9, 0, 0)
            else if (postOfDay === 1) baseDate.setHours(13, 0, 0)
            else baseDate.setHours(19, 0, 0)

            return {
                weekly_plan_id: weeklyPlan.id,
                sequence_number: item.sequence,
                content_type: item.content_type,
                persona: item.persona,
                topic: item.topic,
                theme: item.theme,
                sfw_prompt: item.sfw_prompt,
                nsfw_option: item.nsfw_option,
                gen_sfw: true,
                gen_nsfw: false,
                post_to_ig: true,
                post_to_x: false,
                post_to_fanvue: false,
                caption_draft: item.caption_draft,
                scheduled_at: baseDate.toISOString(),
                status: 'Draft'
            }
        })

        const { error: itemsError } = await supabaseAdmin
            .from('content_items')
            .insert(contentItems)

        if (itemsError) throw itemsError

        await logSystem('SUCCESS', PHASE, `Weekly plan created successfully. ID: ${weeklyPlan.id}`)
        await sendNotification(`✅ <b>Phase 1 Complete:</b> Generated 21 content ideas for the week of ${plan.week_start}. Status: <b>Draft</b>`)

        return { success: true, planId: weeklyPlan.id }
    } catch (error: any) {
        await logSystem('ERROR', PHASE, 'Current job failed', { error: error.message })
        await sendNotification(`❌ <b>Phase 1 Error:</b> ${error.message}`)
        return { success: false, error: error.message }
    }
}
